// What's new, shown once in the control panel after an update (and from Settings → Version).
// Newest first. Keep each line short; the full notes are on GitHub. Languages other than tr fall back to en.
const CHANGES = [
  { v: '1.6.2',
    tr: ['Daha hızlı: kart ve panel her güncellemede bütün sayfayı yeniden kurmuyor; efekt seçince yalnızca değişen bilgi gönderiliyor; oda efekt varlıkları parlaklık ve renk değişimlerinde boşuna hesaplanmıyor.',
      'Ekran düzeltmeleri: küçük tabletlerde ve yan çevrilmiş telefonda oda satırı ve alt çubuk taşmıyor; telefonda kontrol panelindeki efekt listesi ve arama kutusu ekrana sığıyor.',
      'Bildirimler (örneğin "uygulandı") ışık durumu gelince erken kaybolmuyor.'],
    en: ['Faster: the card and panel no longer rebuild the whole page on every update; playing an effect sends only what changed; room effect entities skip work on brightness and colour changes.',
      'Layout fixes: on small tablets and phones held sideways the room row and bottom bar no longer overflow; on phones the control panel effect list and search box fit the screen.',
      'Messages (such as "applied") no longer vanish early when the light state arrives.'],
    de: ['Schneller: Karte und Panel bauen nicht mehr bei jedem Update die ganze Seite neu auf; beim Abspielen wird nur die Änderung gesendet.',
      'Layout-Korrekturen für kleine Tablets, quer gehaltene Handys und das Panel auf dem Handy.'],
    es: ['Más rápido: la tarjeta y el panel ya no reconstruyen toda la página en cada actualización; al reproducir un efecto solo se envía lo que cambió.',
      'Correcciones de diseño en tabletas pequeñas, móviles en horizontal y el panel en el móvil.'],
    fr: ['Plus rapide : la carte et le panneau ne reconstruisent plus toute la page à chaque mise à jour ; lancer un effet n’envoie que ce qui a changé.',
      'Corrections d’affichage sur petites tablettes, téléphones à l’horizontale et le panneau sur téléphone.'] },
  { v: '1.6.1',
    tr: ['Güvenlik güncellemesi: simge dosyası, ışıkların bildirdiği renkler, güncelleme bağlantısı ve paylaşılan düzen artık sıkı denetleniyor. Efekt resmi yükleme ve silme yalnızca yönetici hesabında.'],
    en: ['Security update: the icon file, colours reported by lights, the update link and the shared layout are now strictly checked. Uploading and removing effect pictures is admin only.'],
    de: ['Sicherheitsupdate: Symboldatei, von Lichtern gemeldete Farben, Update-Link und gemeinsames Layout werden jetzt streng geprüft. Effektbilder hochladen und entfernen nur für Administratoren.'],
    es: ['Actualización de seguridad: el archivo de iconos, los colores que envían las luces, el enlace de actualización y el diseño compartido se comprueban estrictamente. Subir y quitar imágenes de efectos solo para administradores.'],
    fr: ['Mise à jour de sécurité : le fichier d’icônes, les couleurs envoyées par les lumières, le lien de mise à jour et la disposition partagée sont désormais strictement vérifiés. Ajouter et retirer des images d’effet est réservé aux administrateurs.'] },
  { v: '1.6.0',
    tr: ['Sesli komut: Assist\'e "salonda kuzey ışıkları efektini aç" ya da "efekti durdur" demen yeter. Ayar gerekmez.',
      'Güncellemeden sonra bu "Yenilikler" penceresi bir kez çıkar; sonra Ayarlar → Sürüm\'den yeniden açılır.',
      'Ayarlar → Yardım → Sorun bildir: sürüm ve cihaz bilgisiyle hazır bir GitHub kaydı açar.'],
    en: ['Voice commands: say "play the aurora effect in the living room" or "stop the effects" to Assist. No setup needed.',
      'After an update this "What\'s new" window shows once; reopen it from Settings → Version.',
      'Settings → Help → Report a problem: opens a GitHub issue with the version and device details filled in.'],
    de: ['Sprachbefehle: Sag Assist „play the aurora effect in the living room“ oder „stop the effects“. Keine Einrichtung nötig.',
      'Nach einem Update erscheint dieses Fenster „Neuerungen“ einmal; danach über Einstellungen → Version.',
      'Einstellungen → Hilfe → Problem melden: öffnet ein GitHub-Issue mit Version und Geräteangaben.'],
    es: ['Comandos de voz: di a Assist «play the aurora effect in the living room» o «stop the effects». Sin configurar nada.',
      'Tras una actualización esta ventana de «Novedades» aparece una vez; luego, desde Ajustes → Versión.',
      'Ajustes → Ayuda → Informar de un problema: abre un issue de GitHub con la versión y los datos del dispositivo.'],
    fr: ['Commandes vocales : dis à Assist « play the aurora effect in the living room » ou « stop the effects ». Aucun réglage.',
      'Après une mise à jour, cette fenêtre « Nouveautés » s’affiche une fois ; ensuite via Réglages → Version.',
      'Réglages → Aide → Signaler un problème : ouvre un ticket GitHub avec la version et les infos de l’appareil.'] },
  { v: '1.5.0',
    tr: ['Ayarlar\'ın başında "Sürüm ve güncelleme": denetle, indir ve Home Assistant\'ı yeniden başlat, hepsi buradan.'],
    en: ['"Version and updates" at the top of Settings: check, download and restart Home Assistant from here.'] },
  { v: '1.4.1',
    tr: ['Kart, sayfa yenilense de son açılan odadan başlar (varsayılan).'],
    en: ['The card opens on the last room you used, even after a reload (default).'] },
  { v: '1.4.0',
    tr: ['Panelde Önizleme anahtarı: açıkken dokunduğun efekt odanın ışıklarında hemen çalar, kapatınca ışıklar eski haline döner.',
      'Güncellemeden sonra eski kartın açılması sorunu giderildi.'],
    en: ['Preview switch in the panel: while on, tapped effects play on the room\'s lights at once; they go back when you switch it off.',
      'Fixed the old card opening after an update.'] },
  { v: '1.3.0',
    tr: ['Yeni telefon düzeni: oda kutusu üstte, durum şeridi, kalın parlaklık çubuğu ve alt sekmeler.'],
    en: ['New phone layout: room box on top, status strip, wide brightness bar and bottom tabs.'] },
  { v: '1.2.0',
    tr: ['Eksik ışıkları tamamla: bir efekti desteklemeyen ışıklara ne yapacaklarını söyle, efekt bütün odada çalsın.'],
    en: ['Fill in lights: tell the lights that lack an effect what to do, so the effect plays in the whole room.'] },
];
